### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bAndie91** [amdonov/lite-idp#4]
Cloud you compose documentation about installing and using this software?

**Comment by amdonov** [comment]
Yes. Although I haven't pushed to this repo in some time, I'm been working on cleaning things up and repackaging. Documentation will also follow. Sorry, but I can't commit to a timeframe just now.

**Comment by amdonov** [comment]
Just finished a major refactor. It's much easier to run and customize now. Documentation is provided. Let me know if you need anything more.
